// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6M7CWAn80VVgrPlDqy_xDt_uzIjrwDw',
    appId: '1:1002706747319:web:f646c366d468defc69f232',
    messagingSenderId: '1002706747319',
    projectId: 'task-app-24956',
    authDomain: 'task-app-24956.firebaseapp.com',
    storageBucket: 'task-app-24956.appspot.com',
    measurementId: 'G-3W9758TJCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtp60lKFy9sCeR-LtQSWQfaUYomJbel00',
    appId: '1:1002706747319:android:5e08048c172a136869f232',
    messagingSenderId: '1002706747319',
    projectId: 'task-app-24956',
    storageBucket: 'task-app-24956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH5W_rXiPr2WDZTcgNasLa7xoedhyGIfY',
    appId: '1:1002706747319:ios:2880c4514fdc7d7069f232',
    messagingSenderId: '1002706747319',
    projectId: 'task-app-24956',
    storageBucket: 'task-app-24956.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );
}
